[SM-32] feat: 로그인된 사용자는 팝업창에서 칵테일 리뷰를 남김 및 삭제 할 수 있다.
prgrms-web-devcourse/Team_Alchomist_ShakeNMatch_BE pull request #7
Opened 2021-12-07 09:36 UTC by wooko5

## 1️⃣ 내용
- 설명: 
로그인된 사용자는 팝업창에서 칵테일 리뷰를 남김 및 삭제 할 수 있다.

## 2️⃣ 참고

2021-12-08 03:19 UTC, p1atina requested changes
고생하셨습니다! 👍🏻

2021-12-08 03:19 UTC, p1atina commented on .github/workflows/deploy-prod.yml
> -          ./deploy.sh
이 내용을 넣어주실수 있으실까요?

2021-12-08 03:19 UTC, p1atina commented on .github/workflows/ec2.yml
> +            ./deploy.sh
ec2.yml 내용을 deploy-prod.yml에 합쳐서 ec2.yml은 삭제해주시고 다시 푸시 부탁드려요!

2021-12-08 04:25 UTC, wooko5 commented on .github/workflows/deploy-prod.yml
> -          ./deploy.sh
넵 알겠습니다!

2021-12-08 04:25 UTC, wooko5 commented on .github/workflows/ec2.yml
> +            ./deploy.sh
넵 알겠습니다!

2021-12-08 05:56 UTC, p1atina approved these changes
고생하셨습니다 👍🏻  💯

2021-12-09 08:45 UTC, SangSun-Park reviewed
확인부탁드려요

2021-12-09 08:45 UTC, SangSun-Park commented on src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
> +
```suggestion
    public Long getId() {
        return id;
    }

```
필요없어요 ㅋㅋㅋㅋㅋ

2021-12-09 08:45 UTC, SangSun-Park commented on src/main/java/com/shake_match/alchomist/review/Review.java
> +    public void setRating(int rating) {
setter는 최대한 사용하지 않는거로 해요

2021-12-09 08:50 UTC, closed without merging

2021-12-09 16:35 UTC, wooko5 commented on src/main/java/com/shake_match/alchomist/review/Review.java
> +    public void setRating(int rating) {
넵 좋습니다!!

2021-12-09 16:36 UTC, wooko5 commented on src/main/java/com/shake_match/alchomist/cocktail/domain/Cocktail.java
> +
ㅋㅋㅋㅋㅋㅋㅋㅋ 그러네요
p.s 타인의 도메인은 유념합시다 ㅎㅎㅎ